export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    XML = "application/xml",
    TEXT = "text/plain",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    OCTET_STREAM = "application/octet-stream",
    PDF = "application/pdf",
    IMAGE_PNG = "image/png",
    IMAGE_JPEG = "image/jpeg",
    IMAGE_GIF = "image/gif",
    IMAGE_SVG = "image/svg+xml",
    AUDIO_MPEG = "audio/mpeg",
    AUDIO_OGG = "audio/ogg",
    VIDEO_MP4 = "video/mp4",
    VIDEO_WEBM = "video/webm",
    APPLICATION_ZIP = "application/zip",
}